doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:OAUTH_DATABASE_URL)%'
            goteo:
                url: '%env(resolve:GOTEO_DATABASE_URL)%'

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
            goteo:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: goteo
                mappings:
                    Goteo:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Goteo
