version: '3.1'
services:

    mariadb_oauth:
        image: 'mariadb:10.2'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=goteo
            - MYSQL_DATABASE=goteo_oauth
            - MYSQL_USER=goteo
            - MYSQL_PASSWORD=goteo
        ports:
            - '12003:3306'

    nginx-proxy:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '52000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        depends_on:
            - mariadb_oauth
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'

networks:
    default:
        external:
            name: goteo_default
