name: "Deployer"
on:
    push:
        branches:
            - main

jobs:
    deployer:
        runs-on: ubuntu-latest

        steps:
            - name: Branch info
              run: echo "Deploying branch main"

            - uses: convictional/trigger-workflow-and-wait@v1.3.0
              with:
                  owner: GoteoFoundation
                  repo: goteo-oauth-deploy
                  workflow_file_name: build.yml
                  inputs: '{"branch": "main"}'
