name: "Deployer"

on:
  push:
    branches:
      - main

jobs:
  deployer:
    runs-on: ubuntu-22.04

    steps:
      - name: Branch info
        run: echo "Deploying branch main"

      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: GoteoFoundation
          repo: goteo-oauth-deploy
          github_token: ${{ secrets.GOTEO_OAUTH_DEPLOY_TOKEN }}
          workflow_file_name: build.yml
          ref: main
