name: "[CI] Test"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-report:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0' ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install NPM packages
        run: |
          sudo npm install grunt -g --prefix=/usr/local
          npm install

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Run Composer Install
        run: composer install --no-interaction

      - name: Run tests
        run: ./run-tests.sh -t config/github-settings.yml tests/
